version: '3'

services:
    # Nginx service
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "9000:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - laravel

    # PHP service
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
        networks:
            - laravel

    # MySQL service
    mysql:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - laravel

    # phpMyAdmin service
    phpmyadmin:
        image: phpmyadmin
        restart: always
        container_name: phpmyadmin
        depends_on:
            - mysql
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: secret
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
